### ISSUE TITLE
Link on the main page not working neither verfied

### ISSUE THREAD

**Issue by sebainones** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-DotNet#24]
Sorry for opening an issue in here.
As I could not open it outside a repo (or at least that I know)  I created here.

So, on the main [page]( https://github.com/AzureADQuickStarts) there's [this  broken link](https://developer.microsoft.com/aad) and in addition, is not **verified**  neither as it happens with [Azure Samples](https://github.com/azure-samples?query=active-directory).
Again, sorry for opening an issue here but I couldn't find a better way.

**Comment by jmprieur** [comment]
Thanks @sebainones
I just fixed it

**Comment by sebainones** [comment]
Your welcome @jmprieur .
I have just checked now and it works fine. Thanks to you!
