### ISSUE TITLE
Azure AD B2C

### ISSUE THREAD

**Issue by MINDoSOFT** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-DotNet#32]
Hello there,

is this sample compatible with Azure AD B2C ?

**Comment by tal32123** [comment]
How about if we don't want to use dotnet core?

**Comment by jmprieur** [comment]
@tal32123 : See https://docs.microsoft.com/azure/active-directory-b2c/quickstart-web-app-dotnet
