### ISSUE TITLE
Link is pointing to review content

### ISSUE THREAD

**Issue by danieldobalian** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-DotNet#6]
One of the links is pointing to a review link for content on docs.ms.

**Comment by RyanTaite** [comment]
I also noticed this. 

The link in question is: `https://review.docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-mobileanddesktopapp-windowsdesktop-intro`

Located in the README.

Sends me to an error page saying I don't have permission. Simply removing `review.` from the link will redirect you to `https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-windesktop`

**Comment by gsacavdm** [comment]
Thank you for your comment @RyanTaite , I've fixed the issue.
